"""Page 8 — Exports & history."""
from __future__ import annotations

from pathlib import Path

import dash_bootstrap_components as dbc
from dash import Input, Output, State, dcc, html
from core.uistate import callback

from app.components import card, guard_alert, labeled, page_header
from core import analysis
from core.session import SESSION

PUB_CHOICES = [
    {"label": "Spatial calibration (HgAr image + positions)",
     "value": "spatial"},
    {"label": "Spectral calibration (spectrum + lines)", "value": "wl"},
    {"label": "Image overview", "value": "overview"},
    {"label": "All 80 spectra of an image", "value": "all"},
    {"label": "Fiber inspection", "value": "fiber"},
]


def _list_outputs():
    ws = Path(SESSION.ensure_workspace())
    out = []
    for sub in ("outputs", ):
        d = ws / sub
        if not d.is_dir():
            continue
        for f in sorted(d.rglob("*")):
            if f.is_file():
                rel = f.relative_to(ws).as_posix()
                out.append((rel, f.stat().st_size))
    return out


def layout():
    return html.Div([
        page_header(
            "Exports & history",
            "Every produced file, and the trace of your analyses.",
            "Interactive graphs export directly from their toolbar (camera "
            "icon → PNG). For figures strictly identical to the notebook "
            "ones (matplotlib), use the publication mode below."),
        card("Produced files", [
            dbc.Button("Refresh the list", id="o-refresh",
                       color="secondary", size="sm", className="mb-2"),
            html.Div(id="o-files"),
        ], icon="bi-folder-check"),
        card("'Publication' figures (original matplotlib rendering)", [
            html.Small("These figures are generated by the original plotting "
                       "functions of your pipeline, identically (same fonts, "
                       "same layouts), and saved as PNG in the exports "
                       "folder.",
                       className="text-muted d-block mb-2"),
            dbc.Row([
                labeled("Figure", dcc.Dropdown(id="o-pub-kind",
                                               options=PUB_CHOICES,
                                               value="wl"), width=4),
                labeled("Image (if applicable)",
                        dcc.Dropdown(id="o-pub-image",
                                     options=[{"label": k, "value": k}
                                              for k in sorted(SESSION.image_dict)],
                                     value=(sorted(SESSION.image_dict)[0]
                                            if SESSION.image_dict else None)),
                        width=3),
                labeled("Fiber 1–80 (if applicable)",
                        dbc.Input(id="o-pub-fiber", type="number", value=63,
                                  min=1, max=80), width=2),
                dbc.Col(dbc.Button("Generate the PNGs", id="o-pub-run",
                                   color="primary", className="mt-4"),
                        width=3),
            ]),
            dcc.Loading(html.Div(id="o-pub-out")),
        ], icon="bi-image"),
        card("Graph display preferences", [
            html.Small("Apply to all interactive graphs. Tip: titles, axis "
                       "titles and legend texts are also editable directly "
                       "by clicking on them on each graph.",
                       className="text-muted d-block mb-2"),
            dbc.Row([
                labeled("Font size",
                        dbc.Input(id="o-pref-font", type="number",
                                  value=SESSION.params.get("PLOT_FONT_SIZE", 13),
                                  min=8, max=26), width=2),
                labeled("Theme",
                        dcc.Dropdown(id="o-pref-template", clearable=False,
                                     value=SESSION.params.get("PLOT_TEMPLATE",
                                                              "plotly_white"),
                                     options=[
                                         {"label": "Light (default)",
                                          "value": "plotly_white"},
                                         {"label": "Minimal",
                                          "value": "simple_white"},
                                         {"label": "Full grid",
                                          "value": "plotly"},
                                         {"label": "Dark",
                                          "value": "plotly_dark"},
                                     ]), width=3),
                dbc.Col(dbc.Button("Apply", id="o-pref-apply",
                                   color="primary", className="mt-4"),
                        width=2),
            ]),
            html.Div(id="o-pref-msg"),
        ], icon="bi-palette"),
        card("Analysis history", [
            dbc.Button("Refresh", id="o-hist-refresh", color="secondary",
                       size="sm", className="mb-2"),
            html.Div(id="o-history"),
        ], icon="bi-clock-history"),
    ])


@callback(Output("o-files", "children"),
          Input("o-refresh", "n_clicks"))
def list_files(_):
    files = _list_outputs()
    if not files:
        return html.Small("No exported file yet. Exports appear here "
                          "(spectra CSVs, .npz/.txt profiles, publication "
                          "figures).", className="text-muted")
    rows = [html.Tr([
        html.Td(html.A(rel, href=f"/download/{rel}")),
        html.Td(f"{size/1024:.0f} kB", className="text-end"),
    ]) for rel, size in files]
    return dbc.Table([html.Thead(html.Tr([html.Th("File (click to "
                                                  "download)"),
                                          html.Th("Size",
                                                  className="text-end")])),
                      html.Tbody(rows)], size="sm", hover=True)


@callback(Output("o-pub-out", "children"),
          Input("o-pub-run", "n_clicks"),
          State("o-pub-kind", "value"), State("o-pub-image", "value"),
          State("o-pub-fiber", "value"),
          prevent_initial_call=True)
def make_publication_figs(_, kind, image, fiber):
    s = SESSION
    if s.calib is None:
        return guard_alert("Run the calibration first (step 2).")
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from core import spectro_functions as sf
    out_dir = s.outputs_dir() / "figures_publication"
    out_dir.mkdir(parents=True, exist_ok=True)
    plt.close("all")
    try:
        s.apply_params_to_sf()
        if kind == "spatial":
            sf.plot_spatial_calibration(s.calib, s.hgar_path)
            stem = "spatial_calibration"
        elif kind == "wl":
            sf.plot_wl_calibration(s.calib)
            if s.params["WL_METHOD"] == "auto":
                sf.plot_wl_calibration_diagnostic(
                    s.calib["mean_calib_spectrum"])
            stem = "spectral_calibration"
        elif kind == "overview":
            if not image:
                return guard_alert("Pick an image.")
            sf.plot_image_overview(s.image_dict[image], calib=s.calib)
            stem = f"{image}_overview"
        elif kind == "all":
            if not image:
                return guard_alert("Pick an image.")
            sp = analysis.get_spectra(image)
            sf.plot_all_spectra(sp, s.calib, image_name=image,
                                use_wl=s.params["USE_WL_AXIS"])
            stem = f"{image}_80spectra"
        elif kind == "fiber":
            if not image:
                return guard_alert("Pick an image.")
            sp, fy, ang = analysis.extract_full(image)
            sf.plot_fiber_inspection(sp, s.calib, int(fiber or 1) - 1,
                                     s.image_dict[image], fiber_y_rot=fy,
                                     angle_deg=ang,
                                     use_wl=s.params["USE_WL_AXIS"])
            stem = f"{image}_fiber{int(fiber or 1)}"
        else:
            return guard_alert("Unknown figure type.")
    except Exception as e:
        plt.close("all")
        return guard_alert(f"Generation failed: {e}", "danger")
    saved = []
    for num in plt.get_fignums():
        f = plt.figure(num)
        p = out_dir / f"{stem}_{num}.png"
        f.savefig(p, dpi=150, bbox_inches="tight")
        saved.append(p)
    plt.close("all")
    if not saved:
        return guard_alert("No figure produced.")
    ws = Path(s.ensure_workspace())
    links = [html.Li(html.A(p.name,
                            href=f"/download/{p.relative_to(ws).as_posix()}"))
             for p in saved]
    s.log_history("publication_figures", {"type": kind, "image": image,
                                          "n_figures": len(saved)})
    return dbc.Alert([f"{len(saved)} figure(s) saved:",
                      html.Ul(links, className="mb-0")], color="success")


@callback(Output("o-history", "children"),
          Input("o-hist-refresh", "n_clicks"))
def show_history(_):
    hist = SESSION.read_history()
    if not hist:
        return html.Small("No analysis recorded yet.",
                          className="text-muted")
    rows = []
    for h in hist[:100]:
        detail = ", ".join(f"{k}={v}" for k, v in h.items()
                           if k not in ("ts", "kind"))
        rows.append(html.Tr([html.Td(h.get("ts", "")),
                             html.Td(dbc.Badge(h.get("kind", "?"),
                                               color="secondary")),
                             html.Td(html.Small(detail))]))
    return dbc.Table([html.Thead(html.Tr([html.Th("Date"), html.Th("Action"),
                                          html.Th("Parameters")])),
                      html.Tbody(rows)], size="sm", hover=True)


@callback(Output("o-pref-msg", "children"),
          Input("o-pref-apply", "n_clicks"),
          State("o-pref-font", "value"), State("o-pref-template", "value"),
          prevent_initial_call=True)
def apply_prefs(_, font, template):
    SESSION.params["PLOT_FONT_SIZE"] = int(font or 13)
    SESSION.params["PLOT_TEMPLATE"] = template or "plotly_white"
    SESSION.save_config()
    return dbc.Alert("Preferences saved — they apply to the next "
                     "displayed graphs.", color="success",
                     className="py-2 mt-2")
